-- Quiz System Database Setup

CREATE DATABASE IF NOT EXISTS quiz_system CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE quiz_system;

-- Users table
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('admin', 'teacher', 'student') NOT NULL DEFAULT 'student',
    status ENUM('active', 'locked') NOT NULL DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- default admin user

INSERT INTO users (username, email, password, role, status)
VALUES ('admin', 'admin@quizsystem.com', '$2y$10$JVW3etjJfnc2scZFDn./QuqNPii5u5Bo91E1kMCqMIc9K1Deu/RGa', 'admin', 'active');

-- Email: admin@quizsystem.com
-- Password: admin123 (stored as hash)

-- Questions table (MCQ bank for quizzes)
CREATE TABLE IF NOT EXISTS questions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    topic VARCHAR(100) NOT NULL,
    difficulty ENUM('easy', 'medium', 'hard') NOT NULL,
    question_text TEXT NOT NULL,
    option_a VARCHAR(255) NOT NULL,
    option_b VARCHAR(255) NOT NULL,
    option_c VARCHAR(255) NOT NULL,
    option_d VARCHAR(255) NOT NULL,
    correct_answer ENUM('A', 'B', 'C', 'D') NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Quiz attempts (one row per student attempt).
-- We keep attempts for both static quizzes and adaptive quizzes in the same table for reporting simplicity.
CREATE TABLE IF NOT EXISTS quiz_attempts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    quiz_id INT NOT NULL,
    topic VARCHAR(100) NOT NULL,
    difficulty ENUM('easy', 'medium', 'hard') NOT NULL,
    score INT NOT NULL,
    total_questions INT NOT NULL,
    percentage DECIMAL(5,2) NOT NULL,
    time_taken INT DEFAULT NULL COMMENT 'seconds',
    attempt_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (quiz_id) REFERENCES quizzes(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Generated questions (LLM-based adaptive MCQs).
-- These are created per-student and per-adaptive-attempt, so they live in a separate table from `questions`.
CREATE TABLE IF NOT EXISTS generated_questions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    topic VARCHAR(100) NOT NULL,
    difficulty ENUM('easy', 'medium', 'hard') NOT NULL,
    question_text TEXT NOT NULL,
    option_a VARCHAR(255) NOT NULL,
    option_b VARCHAR(255) NOT NULL,
    option_c VARCHAR(255) NOT NULL,
    option_d VARCHAR(255) NOT NULL,
    correct_answer ENUM('A', 'B', 'C', 'D') NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    attempt_id INT DEFAULT NULL,
    -- attempt_id is set after the quiz is submitted so we can trace which 5 generated questions were used in a saved attempt.
    INDEX idx_generated_questions_user_id (user_id),
    INDEX idx_generated_questions_attempt_id (attempt_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (attempt_id) REFERENCES quiz_attempts(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Quizzes table (persistent quizzes created by teachers)
CREATE TABLE IF NOT EXISTS quizzes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    topic VARCHAR(100) NOT NULL,
    difficulty ENUM('easy', 'medium', 'hard') NOT NULL,
    created_by INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Per-question results for adaptive (generated) questions
-- We only store per-question correctness for adaptive questions (generated by the LLM).
-- Static quizzes store attempt summary only to keep storage simple.
CREATE TABLE IF NOT EXISTS generated_question_attempts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    attempt_id INT NOT NULL,
    generated_question_id INT NOT NULL,
    user_id INT NOT NULL,
    -- question_hash lets us detect repeats even if the generated_question_id is different between attempts.
    question_hash CHAR(64) NOT NULL COMMENT 'sha256 of normalized question text',
    is_correct TINYINT(1) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_gqa_user_id (user_id),
    INDEX idx_gqa_attempt_id (attempt_id),
    INDEX idx_gqa_question_hash (question_hash),
    FOREIGN KEY (attempt_id) REFERENCES quiz_attempts(id) ON DELETE CASCADE,
    FOREIGN KEY (generated_question_id) REFERENCES generated_questions(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Sample questions (topic: Databases)
INSERT INTO questions (topic, difficulty, question_text, option_a, option_b, option_c, option_d, correct_answer) VALUES
('Databases', 'easy', 'What does SQL stand for?', 'Structured Query Language', 'Simple Query Language', 'Standard Query Language', 'Stored Query Language', 'A'),
('Databases', 'easy', 'Which keyword is used to retrieve data from a table?', 'FETCH', 'SELECT', 'GET', 'OPEN', 'B'),
('Databases', 'easy', 'Which SQL command adds new rows to a table?', 'ADD', 'INSERT', 'CREATE', 'UPDATE', 'B'),
('Databases', 'easy', 'What type of database uses tables and rows?', 'Document', 'Relational', 'Graph', 'Key-value', 'B'),
('Databases', 'easy', 'Which keyword removes rows from a table?', 'REMOVE', 'DROP', 'DELETE', 'CLEAR', 'C'),
('Databases', 'medium', 'What is a primary key used for?', 'To sort results', 'To uniquely identify each row in a table', 'To link tables only', 'To encrypt data', 'B'),
('Databases', 'medium', 'Which clause filters rows in a SELECT statement?', 'FILTER', 'WHERE', 'HAVING', 'LIMIT', 'B'),
('Databases', 'medium', 'Which SQL keyword is used to combine rows from two tables based on a related column?', 'MERGE', 'UNION', 'JOIN', 'APPEND', 'C'),
('Databases', 'medium', 'What is the main purpose of an index in a database?', 'To encrypt data', 'To speed up data retrieval', 'To duplicate data', 'To store backups', 'B'),
('Databases', 'medium', 'Which normal form primarily removes partial dependency on a composite key?', '1NF', '2NF', '3NF', 'BCNF', 'B'),
('Databases', 'hard', 'What does a FOREIGN KEY constraint enforce?', 'Uniqueness of values', 'Referential integrity between tables', 'Default values', 'Index creation', 'B'),
('Databases', 'hard', 'ACID properties are mainly associated with:', 'Indexes', 'Transactions', 'Views', 'Triggers', 'B'),
('Databases', 'hard', 'Which SQL statement is commonly used to inspect a query execution plan?', 'DESCRIBE', 'EXPLAIN', 'ANALYZE TABLE', 'SHOW TABLES', 'B'),
('Databases', 'hard', 'In transaction isolation levels, which issue is prevented by SERIALIZABLE?', 'Dirty reads', 'Lost updates', 'Phantom reads', 'NULL values', 'C'),
('Databases', 'hard', 'A deadlock occurs when:', 'A query runs too fast', 'Two transactions wait on each other to release locks', 'A table has no primary key', 'An index is missing', 'B');

-- Sample questions (topic: Data Structures)
INSERT INTO questions (topic, difficulty, question_text, option_a, option_b, option_c, option_d, correct_answer) VALUES
('Data Structures', 'easy', 'Which data structure works on a First-In-First-Out (FIFO) basis?', 'Stack', 'Queue', 'Tree', 'Graph', 'B'),
('Data Structures', 'easy', 'Which data structure works on a Last-In-First-Out (LIFO) basis?', 'Queue', 'Heap', 'Stack', 'Linked List', 'C'),
('Data Structures', 'easy', 'Which is the typical time complexity to access an element in an array by index?', 'O(1)', 'O(log n)', 'O(n)', 'O(n log n)', 'A'),
('Data Structures', 'easy', 'A linked list node typically contains:', 'Only data', 'Only pointers', 'Data and a pointer/reference', 'Two arrays', 'C'),
('Data Structures', 'easy', 'Which structure represents a hierarchy with a root node?', 'Queue', 'Tree', 'Hash map', 'Matrix', 'B'),
('Data Structures', 'medium', 'Which traversal of a binary search tree outputs values in sorted order?', 'Preorder', 'Inorder', 'Postorder', 'Level order', 'B'),
('Data Structures', 'medium', 'Which data structure is commonly used to implement recursion?', 'Queue', 'Stack', 'Hash table', 'Graph', 'B'),
('Data Structures', 'medium', 'In a max-heap, the value at the root is:', 'The smallest', 'The median', 'The largest', 'Random', 'C'),
('Data Structures', 'medium', 'Average-case time complexity of lookup in a hash table is typically:', 'O(1)', 'O(log n)', 'O(n)', 'O(n log n)', 'A'),
('Data Structures', 'medium', 'Which graph representation is usually more memory-efficient for sparse graphs?', 'Adjacency matrix', 'Adjacency list', '2D array', 'Edge bitmap', 'B'),
('Data Structures', 'hard', 'What is the worst-case time complexity of inserting into a hash table with many collisions (no rehashing)?', 'O(1)', 'O(log n)', 'O(n)', 'O(n log n)', 'C'),
('Data Structures', 'hard', 'Which balancing property is used by AVL trees?', 'Red-black coloring', 'Height difference between subtrees is at most 1', 'Nodes have at most 3 children', 'Keys are stored in arrays', 'B'),
('Data Structures', 'hard', 'Which algorithm is commonly used to find the shortest path in a weighted graph with non-negative weights?', 'DFS', 'BFS', 'Dijkstra\'s algorithm', 'Prim\'s algorithm', 'C'),
('Data Structures', 'hard', 'In Big-O, the time complexity of merge sort is:', 'O(n)', 'O(n log n)', 'O(n^2)', 'O(log n)', 'B'),
('Data Structures', 'hard', 'Which data structure is ideal for implementing an LRU cache efficiently?', 'Array only', 'Queue only', 'Hash map + doubly linked list', 'Binary tree only', 'C');

-- Sample questions (topic: Computer Networks)
INSERT INTO questions (topic, difficulty, question_text, option_a, option_b, option_c, option_d, correct_answer) VALUES
('Computer Networks', 'easy', 'What does IP stand for?', 'Internet Protocol', 'Internal Process', 'Interface Program', 'Integrated Packet', 'A'),
('Computer Networks', 'easy', 'Which device forwards packets based on IP addresses?', 'Switch', 'Router', 'Hub', 'Repeater', 'B'),
('Computer Networks', 'easy', 'Which protocol is used to assign IP addresses automatically?', 'HTTP', 'DNS', 'DHCP', 'FTP', 'C'),
('Computer Networks', 'easy', 'Which port is commonly used for HTTPS?', '21', '53', '80', '443', 'D'),
('Computer Networks', 'easy', 'DNS is mainly used to:', 'Encrypt traffic', 'Translate domain names to IP addresses', 'Route packets', 'Compress data', 'B'),
('Computer Networks', 'medium', 'Which layer of the OSI model is responsible for end-to-end communication and reliability?', 'Network', 'Transport', 'Session', 'Physical', 'B'),
('Computer Networks', 'medium', 'Which protocol provides reliable, connection-oriented transport?', 'UDP', 'TCP', 'ICMP', 'ARP', 'B'),
('Computer Networks', 'medium', 'Which address is used at the data link layer to deliver frames on a LAN?', 'IP address', 'MAC address', 'Port number', 'Hostname', 'B'),
('Computer Networks', 'medium', 'NAT is commonly used to:', 'Increase bandwidth', 'Translate private IPs to a public IP', 'Resolve hostnames', 'Detect malware', 'B'),
('Computer Networks', 'medium', 'What is the main purpose of a subnet mask?', 'Encrypt packets', 'Identify the network and host parts of an IP address', 'Assign ports', 'Measure latency', 'B'),
('Computer Networks', 'hard', 'Which field in an IPv4 packet is decremented by routers to prevent infinite loops?', 'Checksum', 'TTL', 'Sequence number', 'Window size', 'B'),
('Computer Networks', 'hard', 'Which technique reduces collisions in Ethernet by separating collision domains?', 'Broadcasting', 'Switching', 'Flooding', 'Fragmentation', 'B'),
('Computer Networks', 'hard', 'In TCP, what does the three-way handshake establish?', 'DNS resolution', 'A reliable connection and initial sequence numbers', 'Packet routing tables', 'MAC address mapping', 'B'),
('Computer Networks', 'hard', 'Which protocol is used to map an IP address to a MAC address on a local network?', 'ARP', 'ICMP', 'HTTP', 'SNMP', 'A'),
('Computer Networks', 'hard', 'Which congestion control algorithm is associated with TCP and uses additive increase/multiplicative decrease?', 'Stop-and-wait', 'AIMD', 'Token ring', 'CSMA/CD', 'B');